### PR TITLE
Fixes RT#92227 (Moose enum warnings)

### PR DESCRIPTION
**Pull request by zoffixznet**
Fixes https://rt.cpan.org/Ticket/Display.html?id=92227

The new Moose update change the way enum should be called and calling it the old way generates warnings.

### CODE REVIEW

**Comment by perlpunk** [comment]
I vote for this too (the warning is really annoying)

**Comment by Kimamisa** [comment]
Hi !
When will this PR be merged ?

Thanks !

**Comment by maciej-work** [comment]
This causes Net::SSH::Mechanize::Multi to fail since at least 5.14.4, didn't try perlbrewing any further into the past and fixed it myself instead - was going to submit a patch but I see it's fixed here anyway.

**Comment by hakonhagland** [comment]
Yes please release this to cpan :) This seems like very powerful module, so it is a pity it is not up-to-date.

**Pull request merged**
